## Data explorations

In [18]:
import pandas as pd



df_1 = pd.read_csv("raw_data/smhi-opendata_19_71380_199604_200603.csv", sep= ";", skiprows=11)

df_2 = pd.read_csv("raw_data/smhi-opendata_19_71380_200603_201602.csv", sep= ";", skiprows=11)

df_3 = pd.read_csv("raw_data/smhi-opendata_19_71380_201602_202601.csv", sep= ";", skiprows=11)

In [19]:
df_1.columns

Index(['Från Datum Tid (UTC)', 'Till Datum Tid (UTC)', 'Representativt dygn',
       'Lufttemperatur', 'Kvalitet', 'Lufttemperatur.1', 'Kvalitet.1',
       'Unnamed: 7', 'Tidsutsnitt:'],
      dtype='str')

df_1 dates = 					
Tidsperiod (fr.o.m)	Tidsperiod (t.o.m)	Höjd (meter över havet)	Latitud (decimalgrader)	Longitud (decimalgrader)	
1927-04-01 00:00:00	1997-11-30 23:59:59	19.0	162.22.00	112.01.00	
2007-06-01 00:00:00	2026-04-30 23:59:59	21.25	162.22.00	111.48.00

In [24]:
df_1.head(), df_1.tail()

(  Från Datum Tid (UTC) Till Datum Tid (UTC) Representativt dygn  \
 0  1996-04-01 18:00:01  1996-04-02 18:00:00          1996-04-02
 1  1996-04-02 18:00:01  1996-04-03 18:00:00          1996-04-03
 2  1996-04-03 18:00:01  1996-04-04 18:00:00          1996-04-04
 3  1996-04-04 18:00:01  1996-04-05 18:00:00          1996-04-05
 4  1996-04-05 18:00:01  1996-04-06 18:00:00          1996-04-06

    Lufttemperatur Kvalitet  Lufttemperatur.1 Kvalitet.1  Unnamed: 7  \
 0            -4.0        G               2.0          G         NaN
 1             1.0        G               4.4          G         NaN
 2             2.0        G               4.0          G         NaN
 3             0.8        G               3.4          G         NaN
 4             0.2        G               9.1          G         NaN

    Tidsutsnitt:
 0           NaN
 1           NaN
 2           NaN
 3           NaN
 4           NaN  ,
     Från Datum Tid (UTC) Till Datum Tid (UTC) Representativt dygn  \
 603  1997-11-25 18:00:01  1997-11-26 18:00:00          1997-11-26
 604  1997-11-26 18:00:01  1997-11-27 18:00:00          1997-11-27
 605  1997-11-27 18:00:01  1997-11-28 18:00:00          1997-11-28
 606  1997-11-28 18:00:01  1997-11-29 18:00:00          1997-11-29
 607  1997-11-29 18:00:01  1997-11-30 18:00:00          1997-11-30

      Lufttemperatur Kvalitet  Lufttemperatur.1 Kvalitet.1  Unnamed: 7  \
 603            -1.3        G               1.0          G         NaN
 604            -1.6        G               0.7          G         NaN
 605            -2.3        G               2.0          G         NaN
 606             0.5        G               1.6          G         NaN
 607             0.5        G               2.5          G         NaN

      Tidsutsnitt:
 603           NaN
 604           NaN
 605           NaN
 606           NaN
 607           NaN  )

df_2 = 					
Tidsperiod (fr.o.m)	Tidsperiod (t.o.m)	Höjd (meter över havet)	Latitud (decimalgrader)	Longitud (decimalgrader)	
1927-04-01 00:00:00	1997-11-30 23:59:59	19.0	162.22.00	112.01.00	
2007-06-01 00:00:00	2026-04-30 23:59:59	21.25	162.22.00	111.48.00

In [22]:
df_2.head(), df_2.tail()

(  Från Datum Tid (UTC) Till Datum Tid (UTC) Representativt dygn  \
 0  2007-05-31 18:00:01  2007-06-01 18:00:00          2007-06-01
 1  2007-06-01 18:00:01  2007-06-02 18:00:00          2007-06-02
 2  2007-06-02 18:00:01  2007-06-03 18:00:00          2007-06-03
 3  2007-06-03 18:00:01  2007-06-04 18:00:00          2007-06-04
 4  2007-06-04 18:00:01  2007-06-05 18:00:00          2007-06-05

    Lufttemperatur Kvalitet  Lufttemperatur.1 Kvalitet.1  Unnamed: 7  \
 0            10.3        G              16.9          G         NaN
 1            10.0        G              20.1          G         NaN
 2            10.5        G              19.9          G         NaN
 3            14.0        Y              20.5          Y         NaN
 4            16.1        G              20.3          G         NaN

    Tidsutsnitt:
 0           NaN
 1           NaN
 2           NaN
 3           NaN
 4           NaN  ,
      Från Datum Tid (UTC) Till Datum Tid (UTC) Representativt dygn  \
 3192  2016-02-25 18:00:01  2016-02-26 18:00:00          2016-02-26
 3193  2016-02-26 18:00:01  2016-02-27 18:00:00          2016-02-27
 3194  2016-02-27 18:00:01  2016-02-28 18:00:00          2016-02-28
 3195  2016-02-28 18:00:01  2016-02-29 18:00:00          2016-02-29
 3196  2016-02-29 18:00:01  2016-03-01 18:00:00          2016-03-01

       Lufttemperatur Kvalitet  Lufttemperatur.1 Kvalitet.1  Unnamed: 7  \
 3192             0.3        Y               4.1          Y         NaN
 3193             1.5        Y               3.8          Y         NaN
 3194            -0.5        Y               2.6          Y         NaN
 3195            -0.4        Y               1.2          Y         NaN
 3196            -1.3        Y               1.7          Y         NaN

       Tidsutsnitt:
 3192           NaN
 3193           NaN
 3194           NaN
 3195           NaN
 3196           NaN  )

df_3 = 
Tidsperiod (fr.o.m)	Tidsperiod (t.o.m)	Höjd (meter över havet)	Latitud (decimalgrader)	Longitud (decimalgrader)						
1927-04-01 00:00:00	1997-11-30 23:59:59	19.0	162.22.00	112.01.00						
2007-06-01 00:00:00	2026-04-30 23:59:59	21.25	162.22.00	111.48.00

In [23]:
df_3.head(), df_3.tail()

(  Från Datum Tid (UTC) Till Datum Tid (UTC) Representativt dygn  \
 0  2016-02-01 18:00:01  2016-02-02 18:00:00          2016-02-02
 1  2016-02-02 18:00:01  2016-02-03 18:00:00          2016-02-03
 2  2016-02-03 18:00:01  2016-02-04 18:00:00          2016-02-04
 3  2016-02-04 18:00:01  2016-02-05 18:00:00          2016-02-05
 4  2016-02-05 18:00:01  2016-02-06 18:00:00          2016-02-06

    Lufttemperatur Kvalitet  Lufttemperatur.1 Kvalitet.1  Unnamed: 7  \
 0             4.1        Y               7.3          Y         NaN
 1             2.6        Y               6.0          Y         NaN
 2             2.6        Y               4.2          Y         NaN
 3             2.0        Y               3.5          Y         NaN
 4             2.7        Y               5.0          Y         NaN

    Tidsutsnitt:
 0           NaN
 1           NaN
 2           NaN
 3           NaN
 4           NaN  ,
      Från Datum Tid (UTC) Till Datum Tid (UTC) Representativt dygn  \
 3647  2026-01-26 18:00:01  2026-01-27 18:00:00          2026-01-27
 3648  2026-01-27 18:00:01  2026-01-28 18:00:00          2026-01-28
 3649  2026-01-28 18:00:01  2026-01-29 18:00:00          2026-01-29
 3650  2026-01-29 18:00:01  2026-01-30 18:00:00          2026-01-30
 3651  2026-01-30 18:00:01  2026-01-31 18:00:00          2026-01-31

       Lufttemperatur Kvalitet  Lufttemperatur.1 Kvalitet.1  Unnamed: 7  \
 3647            -4.1        Y              -0.6          Y         NaN
 3648            -3.0        Y              -0.8          Y         NaN
 3649            -4.8        Y              -1.9          Y         NaN
 3650            -2.7        Y              -1.7          Y         NaN
 3651            -2.5        Y              -0.4          Y         NaN

       Tidsutsnitt:
 3647           NaN
 3648           NaN
 3649           NaN
 3650           NaN
 3651           NaN  )

In [34]:
df_1["Tidsutsnitt:"].unique(),
df_2["Tidsutsnitt:"].unique(),
df_3["Tidsutsnitt:"].unique()

array([nan])

In [35]:
df_2["Tidsutsnitt:"].unique()

array([nan])

In [36]:
df_3["Tidsutsnitt:"].unique()

array([nan])

In [29]:
df_1["Kvalitet"].unique()

<ArrowStringArray>
['G']
Length: 1, dtype: str

In [30]:
df_2["Kvalitet"].unique()

<ArrowStringArray>
['G', 'Y']
Length: 2, dtype: str

In [31]:
df_3["Kvalitet"].unique()

<ArrowStringArray>
['Y']
Length: 1, dtype: str

In [44]:
df_1_1 = df_1.drop(columns=["Kvalitet", "Kvalitet.1", "Unnamed: 7", "Tidsutsnitt:"])
df_1_1.head()

,Från Datum Tid (UTC),Till Datum Tid (UTC),Representativt dygn,Lufttemperatur,Lufttemperatur.1
0,1996-04-01 18:00:01,1996-04-02 18:00:00,1996-04-02,-4.0,2.0
1,1996-04-02 18:00:01,1996-04-03 18:00:00,1996-04-03,1.0,4.4
2,1996-04-03 18:00:01,1996-04-04 18:00:00,1996-04-04,2.0,4.0
3,1996-04-04 18:00:01,1996-04-05 18:00:00,1996-04-05,0.8,3.4
4,1996-04-05 18:00:01,1996-04-06 18:00:00,1996-04-06,0.2,9.1

In [45]:
df_2_2 = df_2.drop(columns=["Kvalitet", "Kvalitet.1", "Unnamed: 7", "Tidsutsnitt:"])
df_2_2.head()

,Från Datum Tid (UTC),Till Datum Tid (UTC),Representativt dygn,Lufttemperatur,Lufttemperatur.1
0,2007-05-31 18:00:01,2007-06-01 18:00:00,2007-06-01,10.3,16.9
1,2007-06-01 18:00:01,2007-06-02 18:00:00,2007-06-02,10.0,20.1
2,2007-06-02 18:00:01,2007-06-03 18:00:00,2007-06-03,10.5,19.9
3,2007-06-03 18:00:01,2007-06-04 18:00:00,2007-06-04,14.0,20.5
4,2007-06-04 18:00:01,2007-06-05 18:00:00,2007-06-05,16.1,20.3

In [46]:
df_3_3 = df_3.drop(columns=["Kvalitet", "Kvalitet.1", "Unnamed: 7", "Tidsutsnitt:"])
df_3_3.head()

,Från Datum Tid (UTC),Till Datum Tid (UTC),Representativt dygn,Lufttemperatur,Lufttemperatur.1
0,2016-02-01 18:00:01,2016-02-02 18:00:00,2016-02-02,4.1,7.3
1,2016-02-02 18:00:01,2016-02-03 18:00:00,2016-02-03,2.6,6.0
2,2016-02-03 18:00:01,2016-02-04 18:00:00,2016-02-04,2.6,4.2
3,2016-02-04 18:00:01,2016-02-05 18:00:00,2016-02-05,2.0,3.5
4,2016-02-05 18:00:01,2016-02-06 18:00:00,2016-02-06,2.7,5.0

In [50]:
df_3_3["Lufttemperatur"].isna()
df_3_3["Lufttemperatur"].unique()

array([  4.1,   2.6,   2. ,   2.7,   3.8,   3.6,   2.1,   0.8,  -2.2,
        -2. ,  -5.3,  -4.9,   0.1,  -1.9,   1.4,   0.6,   2.3,   0.3,
         0.7,   0. ,   1.5,  -0.5,  -0.4,  -1.3,  -0.3,   0.4,   0.9,
        -0.1,   1.3,   3.1,   2.4,   3. ,   3.7,   3.3,   4.7,   2.9,
         4.8,   5.1,   4.9,   3.5,   5. ,   5.7,   6.7,   5.3,   5.4,
         4.4,   4.6,   5.5,   7.3,   6.8,   6.6,   6.9,   6. ,   7.2,
         3.2,   3.4,   3.9,   4.2,   6.1,   7.1,   7.4,   7.6,  10.3,
        11.3,  12.2,  13.1,  10.8,  10.7,   6.2,   8.5,   8.6,   9.6,
        11.9,  10.4,  12. ,   9. ,  11.4,  10.6,  13.3,  14.2,  15.8,
        16.1,  16.8,  16.5,  16.9,  15. ,  13.4,  16.2,  12.4,  13. ,
         9.9,  12.6,  12.9,  15.7,  14.8,  15.3,  13.9,  14.4,  14.6,
        16.7,  14.7,  15.9,  14. ,  13.5,  12.8,  15.6,  14.3,  14.5,
        15.1,  15.2,  14.1,  13.8,  14.9,  17.4,  18.7,  18.8,  19.5,
        20.2,  17.8,  16.3,  15.4,  17.9,  17.7,  12.5,  17.6,  17.3,
        17.1,  18.2,  17.2,  12.3,  15.5,  16.4,  13.6,  11.2,   5.8,
         8.4,   7. ,   8.2,   4. ,   7.5,   6.3,   9.7,   9.2,   7.9,
         8.3,   1.2,  -3.3,  -3.9,  -2.6,  -1. ,  -2.4,  -0.6,   5.2,
         5.9,   5.6,   1.8,   6.5,  -0.2,   1.6,  -1.8,  -7.2,  -7.3,
        -1.7,  -0.9,  -3. ,   0.2,  -1.6,   0.5,  -3.1,  -2.7,  -1.2,
        -1.1,   2.5,   2.8,   1.9,   4.3,   6.4,   2.2,   7.8,   8.7,
         9.1,   9.4,  10.1,  10. ,   9.5,   9.8,  12.7,  11.7,  11.5,
        12.1,  11.6,  13.2,  13.7,  16. ,  17. ,   9.3,  11.8,   8.9,
        11. ,   8.8,   8.1,  -2.5,  -2.3,   4.5,   1. ,  -0.7,  -4.4,
        -5.1,  -5.9,  -5.2,  -2.1,   1.1,  -0.8,  -5.5,  -4.3,  -6.5,
        -7.6,  -9. , -11.6, -11.1,  -6.7,  -3.8,  -2.8,  -5.8,  -6.9,
        -5.7,  -3.5,  -2.9,  -1.4,   7.7,  11.1,  16.6,  19. ,  18.3,
        20.1,  10.9,  18.4,  18.6,  19.2,  19.7,  19.8,  19.3,  18.9,
        21.3,  20. ,  22.5,  19.1,  20.9,  17.5,  18.1,  10.5,   8. ,
        10.2,   1.7,  -3.4,  -4.1,  19.9,  20.7,  18. ,  19.6,  21.1,
        -6. ,  -4.7,  -3.7,  -5.6,  -1.5,  -3.6,  -8.3,  -9.7,  -7.5,
        -8.2,  -7. ,  -8.5,  19.4,  -3.2,  -4.8,  18.5,  20.3,  -5. ,
        -6.2,  -7.8,  -6.8, -10.3,  -9.9,  -9.4,  -4.5,  -4. ,  20.5,
        20.4,  -5.4,  -7.9])

In [53]:
df_3_3["Lufttemperatur.1"].isna()
df_3_3["Lufttemperatur.1"].unique()

array([ 7.3,  6. ,  4.2,  3.5,  5. ,  5.5,  5.4,  4.7,  4.6,  3.4,  1.3,
        0.6, -0.4, -0.1,  2.9,  2.1,  1.8,  2.4,  4.3,  5.1,  5.2,  4.4,
        4.1,  3.8,  2.6,  1.2,  1.7,  3.2,  2.7,  3.6,  1.6,  3.3,  5.9,
        3.9,  9.6,  7.8,  4.9,  6.1,  6.7,  7.1,  5.7,  9.2,  8.1,  5.6,
        7.4,  6.9,  7. ,  7.5, 10. , 11. ,  7.6,  8.5,  9.9, 10.9, 12.2,
       12.1, 11.1,  8.6, 10.1,  9.5,  6.4,  9.7,  9.3,  8.9,  9. , 10.2,
       10.5, 11.9, 16.1, 18.8, 19.3, 19.4, 20.3, 18.5, 15.4, 10.8, 11.6,
       13.8, 13.4, 14.2, 13.1, 12.7, 17.3, 17. , 19.7, 14.8, 16.3, 18.1,
       20.4, 24.3, 26.1, 24.7, 25.7, 22.6, 24.4, 22.3, 21.1, 18.4, 15.6,
       16.9, 17.9, 19.1, 20. , 19.2, 15.5, 16. , 17.5, 17.4, 19.5, 17.8,
       18.3, 16.5, 16.7, 17.7, 18.7, 18.6, 19.6, 19. , 23.1, 23.8, 23.7,
       22.8, 21. , 20.2, 19.9, 19.8, 18.9, 18.2, 18. , 20.6, 21.6, 17.6,
       20.1, 20.7, 21.3, 22.4, 21.5, 17.2, 15.1, 15.8, 14. , 12.6, 12.9,
       13.5, 11.3, 10.4,  9.1,  8. , 10.3,  8.2, 11.2,  8.8,  4.5,  4. ,
        0.3, -0.5,  0.2,  2.8,  5.8,  8.4,  6.5,  7.9,  7.2,  6.6,  5.3,
        6.3,  8.3, -1.7,  4.8,  0.1,  1.9,  2. ,  2.2,  2.5, -1. , -1.4,
        0.7,  1.1,  3.1,  6.2,  2.3,  1.5,  3.7,  6.8,  8.7, 11.7, 14.6,
       16.6, 13.7, 12.3, 11.5, 20.8, 14.4, 17.1, 16.2, 14.3, 15.7, 15.3,
       15.9, 20.5, 21.8, 22. , 20.9, 16.8, 15. , 14.5, 12.5, 14.7, 14.9,
       14.1, 13.3, 11.4, 13.9, 10.7, 11.8, 13. ,  9.8,  0.5,  3. ,  7.7,
        0.8,  1. , -1.5, -3.6, -1.1, -2.4, -3. , -4.2, -6.6, -5.1, -3.2,
       -1.3, -0.9, -0.6, -0.8, -0.7, 12.4, 16.4,  9.4, 22.2, 21.9, 21.2,
       22.7, 24.1, 26.7, 27.2, 24.5, 23.9, 21.7, 23. , 22.9, 21.4, 23.3,
       24.2, 22.5, 26.2, 23.4, 24. , 25.2, 27.9, 24.6, 25.9, 12.8, 12. ,
       13.2, 13.6,  1.4, -0. , 10.6, 22.1, 28. , 28.2, 27. , 25.1, 25.3,
       23.2, 15.2, 26.3, 23.6, 24.8, 27.5, -2. , -1.6, -0.2,  0.4, -5.2,
       -4.8, -2.9, -3.7, -4.4, -2.5, 25.8, -3.1, 25. , 27.6, -0.3, -3.3,
       -1.2, -1.9, -3.8, -2.6, -7.3, -8.1, -6.2,  0.9, 27.3, 25.5, 27.4,
       -2.7, -4.3])

In [51]:
df_2_2["Lufttemperatur"].isna()
df_2_2["Lufttemperatur"].unique()

array([ 10.3,  10. ,  10.5,  14. ,  16.1,  16.2,  16.9,  17.1,  18.1,
        19.1,  20.4,  17.7,  13.3,  11.9,  12.1,  12.9,  11.4,  12.5,
        14.1,  15.9,  14.2,  14.9,  15.2,  16. ,  12.2,  13.6,  13.2,
        12.8,  14.6,  12.7,  13.5,  14.7,  14.8,  14.5,  13.9,  13.4,
        15.3,  17.6,  14.3,  11.8,  14.4,  15.4,  13.8,  13. ,  16.8,
        17. ,  17.5,  18.5,  18.2,  18.8,  17.4,  16.7,  16.6,  16.3,
        16.4,  15.7,  15. ,  10.9,  11.3,  11.2,  11.1,   9.2,  12.4,
        10.8,  11.7,   9.7,  10.1,  12. ,  10.7,   9.1,  12.3,   9.9,
        10.2,  10.6,   8. ,   8.9,   7.6,   9.5,   7.4,   6.7,   4.6,
        11.5,   7.1,   5.8,   7.8,   8.1,   7. ,   4.4,   5.9,   5. ,
         7.9,   9. ,   4.3,   7.5,   6. ,   7.3,   4.5,   2. ,   0.5,
         1.4,   0.7,   3.8,   5.6,   5.7,   3.9,   3.6,   2.9,   4.2,
         1.8,  -0.3,   1.7,   1.5,   5.1,   5.3,   6.2,   4.7,   4.1,
         6.9,   5.4,   0. ,   0.1,   1.9,   0.4,   1.1,  -0.1,  -0.9,
        -1.1,   2.7,   0.2,   0.3,   3.1,   1.3,  -1.3,  -1.7,  -2.1,
         2.1,   2.2,   3.4,   3.7,   3.2,   4.9,  -0.6,   2.4,   3. ,
         1.6,   3.5,  -0.4,  -1.2,   5.2,   4.8,   2.3,   2.5,   3.3,
         1. ,   2.6,   5.5,  -0.2,  -3.9,  -5.3,  -2. ,  -4.1,  -0.5,
         6.1,   7.2,   8.7,   8.4,   8.8,  11.6,  13.7,   9.6,   9.8,
         8.5,  15.6,  17.9,  13.1,  17.8,  15.1,  15.8,  19.2,  19. ,
        19.9,  21.4,  20.3,  19.6,  20.7,  20.6,  15.5,   8.6,   8.3,
        11. ,  10.4,   0.8,   0.6,   6.5,   8.2,   6.3,  -1. ,   0.9,
         2.8,  -1.5,  -1.9,  -3. ,  -2.4,  -3.7,  -5.8,  -8. ,  -1.6,
        -3.3,  -4.8,  -3.8,  -0.7,  -6.4,  -4.6,  -2.9,  -5.7,  -3.6,
        -4.2,  -2.7,  -2.6,   1.2,  -1.4,   7.7,   9.3,   9.4,  16.5,
        18. ,  18.7,  18.3,  20.5,  21.3,  18.4,  17.2,  17.3,  12.6,
         6.8,   6.6,  -6. ,  -5.1,  -5.5,  -6.1,  -4. ,  -6.9, -10.7,
        -7.4,  -8.2,  -8.9,  -2.3,  -9.4, -10.2, -10. , -11.7, -12.5,
        -8.1,  -8.3,  -7.1,  -6.6,  -2.2,  -1.8,  -3.1,  -2.5,  -5.9,
        -0.8,  -7.8, -12.1, -11.1,  -7. ,  -8.6,  -5.2,  -5. ,  -4.9,
        -7.5,  -7.9,  -9.5,  -3.2,  -7.2, -12.4, -12.7,  -3.5,   4. ,
         6.4,  -6.7,  -8.4,  -5.6,  -4.3, -10.6,  -7.3,  -8.7,  -9.1,
       -10.9, -11.5,  -9.2,  -6.5,  -9.3,  -4.4,  -7.7,  -8.5,  -2.8,
        19.7, -11.2, -11.6,  -9. ,  -6.8,  -7.6,  -6.3,  -6.2,  18.9,
        -4.5,  20.1,  20.2,  20.9,  20.8,  19.8,  19.5,  19.4,  -5.4,
        -4.7])

In [52]:
df_3_3["Lufttemperatur"].isna()
df_3_3["Lufttemperatur"].unique()

array([  4.1,   2.6,   2. ,   2.7,   3.8,   3.6,   2.1,   0.8,  -2.2,
        -2. ,  -5.3,  -4.9,   0.1,  -1.9,   1.4,   0.6,   2.3,   0.3,
         0.7,   0. ,   1.5,  -0.5,  -0.4,  -1.3,  -0.3,   0.4,   0.9,
        -0.1,   1.3,   3.1,   2.4,   3. ,   3.7,   3.3,   4.7,   2.9,
         4.8,   5.1,   4.9,   3.5,   5. ,   5.7,   6.7,   5.3,   5.4,
         4.4,   4.6,   5.5,   7.3,   6.8,   6.6,   6.9,   6. ,   7.2,
         3.2,   3.4,   3.9,   4.2,   6.1,   7.1,   7.4,   7.6,  10.3,
        11.3,  12.2,  13.1,  10.8,  10.7,   6.2,   8.5,   8.6,   9.6,
        11.9,  10.4,  12. ,   9. ,  11.4,  10.6,  13.3,  14.2,  15.8,
        16.1,  16.8,  16.5,  16.9,  15. ,  13.4,  16.2,  12.4,  13. ,
         9.9,  12.6,  12.9,  15.7,  14.8,  15.3,  13.9,  14.4,  14.6,
        16.7,  14.7,  15.9,  14. ,  13.5,  12.8,  15.6,  14.3,  14.5,
        15.1,  15.2,  14.1,  13.8,  14.9,  17.4,  18.7,  18.8,  19.5,
        20.2,  17.8,  16.3,  15.4,  17.9,  17.7,  12.5,  17.6,  17.3,
        17.1,  18.2,  17.2,  12.3,  15.5,  16.4,  13.6,  11.2,   5.8,
         8.4,   7. ,   8.2,   4. ,   7.5,   6.3,   9.7,   9.2,   7.9,
         8.3,   1.2,  -3.3,  -3.9,  -2.6,  -1. ,  -2.4,  -0.6,   5.2,
         5.9,   5.6,   1.8,   6.5,  -0.2,   1.6,  -1.8,  -7.2,  -7.3,
        -1.7,  -0.9,  -3. ,   0.2,  -1.6,   0.5,  -3.1,  -2.7,  -1.2,
        -1.1,   2.5,   2.8,   1.9,   4.3,   6.4,   2.2,   7.8,   8.7,
         9.1,   9.4,  10.1,  10. ,   9.5,   9.8,  12.7,  11.7,  11.5,
        12.1,  11.6,  13.2,  13.7,  16. ,  17. ,   9.3,  11.8,   8.9,
        11. ,   8.8,   8.1,  -2.5,  -2.3,   4.5,   1. ,  -0.7,  -4.4,
        -5.1,  -5.9,  -5.2,  -2.1,   1.1,  -0.8,  -5.5,  -4.3,  -6.5,
        -7.6,  -9. , -11.6, -11.1,  -6.7,  -3.8,  -2.8,  -5.8,  -6.9,
        -5.7,  -3.5,  -2.9,  -1.4,   7.7,  11.1,  16.6,  19. ,  18.3,
        20.1,  10.9,  18.4,  18.6,  19.2,  19.7,  19.8,  19.3,  18.9,
        21.3,  20. ,  22.5,  19.1,  20.9,  17.5,  18.1,  10.5,   8. ,
        10.2,   1.7,  -3.4,  -4.1,  19.9,  20.7,  18. ,  19.6,  21.1,
        -6. ,  -4.7,  -3.7,  -5.6,  -1.5,  -3.6,  -8.3,  -9.7,  -7.5,
        -8.2,  -7. ,  -8.5,  19.4,  -3.2,  -4.8,  18.5,  20.3,  -5. ,
        -6.2,  -7.8,  -6.8, -10.3,  -9.9,  -9.4,  -4.5,  -4. ,  20.5,
        20.4,  -5.4,  -7.9])

In [57]:
df = pd.concat([df_3_3,df_1_1, df_2_2], ignore_index= True)
df.shape
df.head()
df.columns

Index(['Från Datum Tid (UTC)', 'Till Datum Tid (UTC)', 'Representativt dygn',
       'Lufttemperatur', 'Lufttemperatur.1'],
      dtype='str')

In [ ]:
df.to_csv("../clean_data/cleand_smhi.csv")

OSError: Cannot save file into a non-existent directory: 'clean_data'